app/models/users.py
from datetime import datetime

from flask import current_app, flash
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import BadSignature, SignatureExpired
from app.extensions import db, login_manager
from flask_babel import lazy_gettext as _
from flask_login import UserMixin


class Base(object):
    def save(self):
        try:
            db.session.add(self)
            db.session.commit()
        except:
            db.session.rollback()


class User(Base, UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), nullable=False, unique=True)
    password_hash = db.Column(db.String(128), nullable=False)
    email = db.column(db.String(64), nullable=False, unique=True)
    confirm = db.column(db.Boolean, default=False)
    create_time = db.Column(db.DateTime, doc=_('创建时间'), default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        self.password_hash = generate_password_hash(password)
        self.email = email

    def __repr__(self):
        return self.username

    # 密码字段保护
    @property
    def password(self):
        raise AttributeError(_('密码是不可读属性'))

    # 设置密码， 加密存储
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 生成激活token
    def generate_activate_token(self):
        # 创建用于生成token的类，需要传递秘钥和有效期expires_in默认=3600,expires_in=60
        s = Serializer(current_app.config['SECRET_KEY'])
        return s.dumps({'id': self.id})

    # 生成任意的token
    @staticmethod
    def generate_token(dict_data):
        s = Serializer(current_app.config['SECRET_KEY'])
        return s.dumps(dict_data)

    # 检查任意token是否有效,返回真实词典数据
    @staticmethod
    def check_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            dict_data = s.loads(token)
        except SignatureExpired:
            flash(_('邮件已过期'))
            return False
        except BadSignature:
            flash(_('无效的验证邮箱'))
            return False
        return dict_data

    # 账户激活，因为激活时还不知道是哪个用户
    @staticmethod
    def check_activate_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            flash(_('激活邮件已过期'))
            return False
        except BadSignature:
            flash(_('无效的激活'))
            return False
        user = User.query.get(data.get('id'))
        if not user:
            flash(_('激活的账号不存在'))
            return False
        # 激活
        if not user.confirm:
            user.confirm = True
            db.session.add(user)
        return True

    # 密码校验
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(uid):
        return User.query.get(int(uid))

app/forms/users.py
from flask_login import current_user
from flask_wtf import FlaskForm
from sqlalchemy.testing.pickleable import User
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, \
    ValidationError
from flask_babel import gettext as _


class RegisterForm(FlaskForm):
    username = StringField(_('用户名'), validators=[
        DataRequired(message=_('请填写用户名')),
        Length(4, 20, message=_('长度在4到20个字符之间'))
    ])
    email = StringField('邮箱', validators=[
        DataRequired(message=_('请填写邮箱')),
        Email(message=_('请填写正确的邮箱格式'))
    ])
    password = PasswordField('密码', validators=[
        DataRequired(message=_('请填写密码')),
        Length(8, 20, message=_('密码长度在8到20个字符之间')),
        EqualTo('confirm', message=_('密码不一致'))
    ])
    confirm = PasswordField(_('密码确认'))
    submit = SubmitField(_('注册'))

    # 检验username是否存在
    def validate_username(self, field):
        user = User.query.filter_by(username=field.data).first()
        if user:
            raise ValidationError(_('用户名已存在'))

    def validate_email(self, field):
        user = User.query.filter_by(email=field.data).first()
        if user:
            raise ValidationError(_('邮箱已存在'))


class LoginForm(FlaskForm):
    username = StringField(_('用户名或邮箱'), validators=[
        DataRequired(message=_('用户名不能为空'))
    ])
    password = PasswordField(_('密码'), validators=[
        DataRequired(message=_('密码不能为空'))
    ])
    remember = BooleanField(_('记住我'), default=True)
    submit = SubmitField(_('登录'))


class UserPasswordForm(FlaskForm):
    oldpwd = PasswordField(_('原密码'), validators=[
        DataRequired(message=_('原密码不能为空'))
    ])
    newpwd = PasswordField(_('新密码'), validators=[
        DataRequired(message=_('请填写新密码')),
        Length(8, 20, message=_('密码长度8到20个字符')),
        EqualTo('confirm', message=_('密码不一致'))
    ])
    confirm = PasswordField(_('密码确认'))
    submit = SubmitField(_('提交'))

    def validate_oldpwd(self, field):
        user = current_user._get_current_object()
        if not user.verify_password(field.data):
            raise ValidationError(_('原密码错误'))

    def validate_newpwd(self, field):
        user = current_user._get_current_object()
        if user.verify_password(field.data):
            raise ValidationError(_('新旧密码不能一样'))


# 填写新邮箱来修改邮箱
class EmailForm(FlaskForm):
    email = StringField(_('新邮箱'), validators=[
        DataRequired(message=_('请填写新邮箱')),
        Email(message=_('请填写正确的邮箱格式'))
    ])
    submit = SubmitField(_('提交'))


# 用来提交用户名或邮箱来重置密码
class EUForm(FlaskForm):
    username = StringField(_('用户名或有效的邮箱'), validators=[
        DataRequired(message=_('用户名不能为空'))
    ])
    submit = SubmitField(_('下一步'), render_kw={'style': "float: right"})


# 用来提交验证码
class AuthCodeForm(FlaskForm):
    authcode = StringField(_('验证码'), validators=[
        DataRequired(message=_('验证码不能为空'))
    ])
    submit = SubmitField(_('提交'), render_kw={'style': "float: right"})


# 重置密码
class ResetPwdForm(FlaskForm):
    password = PasswordField(_('新密码'), validators=[
        DataRequired(message=_('请填写密码')),
        Length(8, 20, message=_('密码长度8到20个字符')),
        EqualTo('confirm', message=_('密码不一致'))
    ])
    confirm = PasswordField(_('密码确认'))
    submit = SubmitField(_('确定'), render_kw={'style': "float: right"})

app/blueprints/users.py
from flask import Blueprint, request, flash, url_for, redirect, render_template
from flask_login import login_user, logout_user, current_user
from sqlalchemy import or_
from flask_babel import gettext as _trans

from app.email import send_mail
from app.extensions import db
from app.forms import RegisterForm, LoginForm, UserPasswordForm, EUForm, \
    AuthCodeForm, ResetPwdForm, EmailForm
from app.models import User

users = Blueprint('users', __name__)


@users.route('/register/', method=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data,
                    email=form.email.data)
        user.save()
        token = user.generate_activate_token()
        send_mail([user.email], _trans('激活邮件'), 'email/activate',
                  username=user.username, token=token)
        flash(_trans('注册成功'))
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


# 激活
@users.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        flash(_trans('账号已激活'))
        return redirect(url_for('main.index'))
    else:
        flash(_trans('激活失败'))
        return redirect(url_for('main.index'))


# 用户登录
@users.route('/login/', method=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        user = User.query.filter(or_(User.username == username,
                                     User.email == username)).first()
        if not user:
            flash(_trans('用户名或密码错误'))
        elif not user.confirm:
            flash(_trans('用户未被激活,请先激活在登录'))
        elif not user.verify_password(form.password.data):
            flash(_trans('用户名或密码错误'))
        else:
            login_user(user, remember=form.remember.data)
            flash(_trans('登录成功'))
            return redirect(url_for('main.index', next=request.args.get(
                'next')))
    return render_template('users/login.html', form=form)


@users.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


# 显示用户信息
@users.route('/profile/')
def profile():
    return render_template('users/profile.html')


@users.route('/change_password/', method=['GET', 'POST'])
def change_password():
    form = UserPasswordForm()
    if form.validate_on_submit():
        newpwd = form.newpwd.data
        user = current_user._get_current_object()
        user.password = newpwd
        db.session.add(user)
        logout_user()
        flash(_trans('密码修改成功，请重新登录'))
        return redirect(url_for('users.login'))
    return render_template('users/change_password.html', form=form)


# 生成随机字符串
def random_string(length=16):
    import random
    import string
    base_str = string.ascii_letters + string.digits + '!@#$%^&*-_'
    return ''.join(random.choice(base_str) for _ in range(length))


@users.route('/reset_password/', method=['GET', 'POST'])
def reset_password():
    form1 = EUForm()
    global authcode
    authcode = random_string(8)
    if form1.validate_on_submit():
        global Uname
        Uname = username = form1.username.data
        user = User.query.filter(or_(User.username == username, User.email ==
                                     username)).first()
        if user:
            send_mail([user.email], _trans('验证码邮件'), 'email/authcode',
                      username=user.username, authcode=authcode)
            flash(_trans('验证码邮件已发送，请查收'))
            return redirect(url_for('users.reset_password2'))
        else:
            flash(_trans('请输入正确的用户名或邮箱'))
    return render_template('users/reset_password.html', form1=form1)


@users.route('/reset_password2', method=['GET', 'POST'])
def reset_password2():
    form2 = AuthCodeForm()
    if form2.validate_on_submit():
        if authcode == form2.authcode.data:
            return redirect(url_for('users.reset_password3'))
        else:
            flash(_trans('验证码错误'))
    return render_template('users/reset_password2.html', form2=form2)


@users.route('/reset_password3', method=['GET', 'POST'])
def reset_password3():
    form3 = ResetPwdForm()
    user = User.query.filter(or_(User.username ==  Uname, User.email ==
                                 Uname)).first()
    if form3.validate_on_submit():
        newpwd = form3.password.data
        if not user.verify_password(newpwd):
            user.password = newpwd
            db.session.add(user)
        logout_user()
        return redirect(url_for('users.reset_password4'))
    return render_template('users/reset_password3.html', form3=form3)


@users.route('/reset_password4')
def reset_password4():
    return render_template('users/reset_password4.html')


# 修改邮箱
@users.route('/change_email/', method=['GET', 'POST'])
def change_email():
    form = EmailForm()
    if form.validate_on_submit():
        newemail = form.email.data
        infoDict = {'user_id': current_user.id, 'newemail': newemail}
        token = User.generate_token(infoDict)
        send_mail([newemail], _trans('修改邮箱邮件'), 'email/change_email',
                  username=current_user.username, token=token)
        flash(_trans('邮件已发送，注意查收'))
    return render_template('users/change_email.html', form=form)


@users.route('/success_change_email/token/')
def success_change_email(token):
    data = User.check_token(token)
    if data:
        user = User.query.get(data['user_id'])
        if user.email != data['newemail']:
            user.email = data['newemail']
            db.session.add(user)
        flash(_trans('邮箱修改成功，请查看账号信息'))
        return redirect(url_for('main.index'))
    else:
        flash(_trans('邮件已失效，请重新发送'))
        return redirect(url_for('users.change_email'))

app/templates/users/change_email.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("修改邮箱") {% endblock %}

{% block page_content %}
    <h1 align="center">_("修改邮箱")</h1>
    <hr>
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/users/change_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("密码修改") {% endblock %}

{% block page_content %}
    <h1 align="center">_("修改密码")</h1>
    <hr>
    {{ wtf.quick_form(form) }}
    <p style="margin-top: 10px;display: inline-block">
        _("如果忘记原密码，建议通过<a href="{{ url_for('users.reset_password') }}">找回密码</a>
        的方式来完成修改密码")</p>
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("用户登录") {% endblock %}

{% block page_content %}
    <h1 align="center">_("用户登录")</h1>
    <hr>
    {{ wtf.quick_form(form,button_map={'submit':'primary'}) }}
    <div>
        <div style="margin-top: 5px">
            <span>
            _("没有账号？")<a href="{{ url_for('users.register') }}">
                _("立即注册")</a>
            </span>
        </div>
        <div style="float: right">
            <span>
            <a href="{{ url_for('users.reset_password') }}">
                _("忘记密码？")
            </a>
            </span>
        </div>
    </div>
{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}_("账号详情"){% endblock %}

{% block page_content %}
    <h1 align="center">_("用户详细信息")</h1>
    <hr>
    <div class="form-group">
        <label for="inputUsername">_("用户名")</label>
        <input type="text" class="form-control" id="inputUsername" value="{{ current_user.username }}" readonly>
    </div>
    <div class="form-group">
        <label for="inputEmail">_("邮箱")</label>
        <input type="text" class="form-control" id="inputEmail" value="{{ current_user.email }}" readonly>
    </div>
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("用户注册") {% endblock %}

{% block page_content %}
    <h1 align="center">_("用户注册")</h1>
    <hr>
    {{ wtf.quick_form(form,button_map={'submit':'primary'}) }}

    <div align="center">
        <a href="{{ url_for('users.login') }}">_("已有账号登录")</a>
    </div>
{% endblock %}

app/templates/users/reset_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("重置密码") {% endblock %}

{% block page_content %}
    <h1 align="center">_("重置密码")</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><a
                    href="{{ url_for('users.reset_password') }}">①_("输入用户名或邮箱")</a></li>
            <li role="presentation"><a href="#">②_("输入验证码")</a></li>
            <li role="presentation"><a href="#">③_("设置密码")</a></li>
            <li role="presentation"><a href="#">④_("完成")</a></li>
        </ul>
    </div>
    <hr>
    {{ wtf.quick_form(form1,button_map={'submit':'primary'}) }}
{% endblock %}

app/templates/users/reset_password3.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("重置密码") {% endblock %}

{% block page_content %}
    <h1 align="center">_("重置密码")</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation"><a href="{{ url_for('users.reset_password') }}">①_("输入用户名或邮箱")</a></li>
            <li role="presentation"><a href="#">②_("输入验证码")</a></li>
            <li role="presentation" class="active"><a href="#">③_("设置密码")</a></li>
            <li role="presentation"><a href="#">④_("完成")</a></li>
        </ul>
    </div>
    <hr>
    {{ wtf.quick_form(form3,button_map={'submit':'primary'}) }}
{% endblock %}

app/templates/users/reset_password4.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("重置密码") {% endblock %}

{% block page_content %}
    <h1 align="center">_("重置密码")</h1>
    <div align="center">
        <ul class="nav nav-pills">
           <li role="presentation"><a href="{{ url_for('users.reset_password') }}">①_("输入用户名或邮箱")</a></li>
            <li role="presentation"><a href="#">②_("输入验证码")</a></li>
            <li role="presentation"><a href="#">③_("设置密码")</a></li>
            <li role="presentation" class="active"><a href="#">④_("完成")</a></li>
        </ul>
    </div>
    <hr>
    <h2>_("密码重置完成"),<a href="{{ url_for('users.login') }}">_("马上登录")</a></h2>
{% endblock %}

app/templates/users/reset_passwrod2.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} _("重置密码") {% endblock %}

{% block page_content %}
    <h1 align="center">_("重置密码")</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation"><a
                    href="{{ url_for('users.reset_password') }}">①_("输入用户名或邮箱")</a></li>
            <li role="presentation" class="active"><a href="#">②_("输入验证码")</a></li>
            <li role="presentation"><a href="#">③_("设置密码")</a></li>
            <li role="presentation"><a href="#">④_("完成")</a></li>
        </ul>
    </div>
    <hr>
    {{ wtf.quick_form(form2,action=url_for('users.reset_password2'),button_map={'submit':'primary',}) }}
{% endblock %}